name: Clang Latest

on:
  push:
  schedule:
    - cron: '0 0 * * *'

env:
    GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
    CHATID: ${{ secrets.CHATID }}
    TOKEN: ${{ secrets.TOKEN }}
  
jobs:
  goBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Building
      run: |
        bash build-tc.sh
