name: WeebX Clang

on:
  workflow_dispatch:

env:
    GIT_TOKEN: ${{ secrets.GITLAB_TOKEN }}
  
jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Good Revision
      run: |
        bash buildCI.sh
