name: My Workflow

on:
    workflow_dispatch:
    
env:
    LLVM_NAME: ${{ secrets.LLVM_NAME }}
    GITLAB_TOKEN_EMAIL: ${{ secrets.GITLAB_TOKEN_EMAIL }}
    GITLAB_TOKEN_USERNAME: ${{ secrets.GITLAB_TOKEN_USERNAME }}
    GITLAB_TOKEN_TOKEN: ${{ secrets.GITLAB_TOKEN_TOKEN }}
    GITLAB_TOKEN_PUSH_REPO_URL: ${{ secrets.GITLAB_TOKEN_PUSH_REPO_URL }}
    TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
    TG_TOKEN: ${{ secrets.TG_TOKEN }}

jobs:
  goBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setting up Git config
      run: |
        git config --global user.name "$GH_USERNAME"
        git config --global user.email "$GH_EMAIL"
        git config --global lfs.locksverify true
    - name: Building
      run: |
        sudo apt-get install -y cmake ninja-build python3-pip libffi-dev python3-dev
        bash tc-build.sh -j $(nproc)
