name: Clang Latest

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
          LLVM_NAME: ${{ secrets.LLVM_NAME }}
          GL_TOKEN: ${{ secrets.GH_TOKEN }}
          GL_PUSH_REPO_URL: ${{ secrets.GL_PUSH_REPO_URL }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
  
jobs:
  goBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Building
      run: |
        bash build-tc.sh
