name: Clang Latest

on:
  push:
  schedule:
    - cron: '0 0 * * *'

env:
    GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
    TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
    TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  
jobs:
  goBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Building
      run: |
        bash buildCI.sh
