
name: WeebX Clang Latest

on:
  push:
  schedule:
    - cron: '0 0 * * *'

env:
    GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
    TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
    TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  
jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Good Revision
      run: |
        bash buildCI.sh
